### ISSUE TITLE
Calling wasm modules compiled by javy

### ISSUE THREAD

**Issue by F21** [bytecodealliance/javy#111]
I've been playing around with the examples for javy, in particular the one in the readme:
```js
function foo(input) {
    return { foo: input.n + 1, newBar: input.bar + "!" };
}

Shopify = {
    main: foo,
};
```
Using wasmer from the cli, it easy to pass in a string to the main function: `echo '{ "n": 2, "bar": "baz" }' | wasmer shopify.wasm`

Inspecting the compiled file, I can see the following exported functions:
```
Type: wasm
Size: 999.3 KB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_read": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."clock_time_get": [I32, I64, I32] -> [I32]
    "wasi_snapshot_preview1"."proc_exit": [I32] -> []
    "wasi_snapshot_preview1"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_seek": [I32, I64, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_close": [I32] -> [I32]
    "wasi_snapshot_preview1"."fd_fdstat_get": [I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "_start": [] -> []
    "main": [I32, I32] -> [I32]
  Memories:
    "memory": not shared (22 pages..)
  Tables:
  Globals:
    "__heap_base": I32 (constant)
    "__data_end": I32 (constant)
```
I want to call the module from go. In order to pass in a string, I need to allocate memory (example here: https://github.com/tetratelabs/wazero/blob/main/examples/allocation/tinygo/greet.go#L67). The function signature for main `"main": [I32, I32] -> [I32]` looks like it takes a pointer to memory and a length.

Since the module compiled by javy does not have `malloc` or `free` functions exported, how can this be done?
How is `wasmer` able to call the module with a string?

Ref: https://github.com/tetratelabs/wazero/issues/591 and https://github.com/tetratelabs/wazero/issues/592

**Comment by saulecabrera** [comment]
Hey @F21, 

The default implementation of Javy is by design WASI-only, meaning that the generated modules don't expose or expect custom hostcalls, instead it uses `stdin`/`stdout` for input and output. In your case, you'd need to programatically pass in the string (as an array of bytes) from go through `stdin`.  I'm not familiar with Wasmer's API, but with wasmtime-wasi, this can be easily done via https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/struct.WasiCtx.html#method.set_stdin
