### ISSUE TITLE
can javy used to compile a nodejs project ?

### ISSUE THREAD

**Issue by liufeihe** [bytecodealliance/javy#184]
i think this line is the reason throw error, 

**const mathjs = require('mathjs');**

so the javy can not used to compile a nodejs project ?

**the errors is below:** 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught ReferenceError: 'require' is not defined
    at <eval> (function.mjs:1)
', crates/core/src/main.rs:40:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to run main module `index.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x112d1 - <unknown>!<wasm function 278>
           1: 0x10a99 - <unknown>!<wasm function 277>
           2: 0x109e5 - <unknown>!<wasm function 276>
           3: 0x35c4 - <unknown>!<wasm function 74>
           4: 0x131b - <unknown>!<wasm function 39>
           5: 0x23d6 - <unknown>!<wasm function 55>
           6: 0xab5b - <unknown>!<wasm function 168>
           7: 0xa9ca - <unknown>!<wasm function 167>
           8: 0xb557a - <unknown>!<wasm function 1125>
    2: wasm trap: wasm `unreachable` instruction executed

**Comment by jeffcharles** [comment]
No, Javy cannot be used to compile a NodeJS project.

**Comment by jeffcharles** [comment]
What you may be able to do if you want to use `require` to work with JS packages, is use a transpiler like [rollup.js](https://rollupjs.org/guide/en/) to convert your code and its dependencies to a single JS file and then execute that with Javy. However, NodeJS APIs that are outside of what QuickJS provides are not supported.

**Comment by liufeihe** [comment]
> What you may be able to do if you want to use `require` to work with JS packages, is use a transpiler like [rollup.js](https://rollupjs.org/guide/en/) to convert your code and its dependencies to a single JS file and then execute that with Javy. However, NodeJS APIs that are outside of what QuickJS provides are not supported.

thanks, it's very helpful.
