### ISSUE TITLE
Explore if we can introduce fuzzing

### ISSUE THREAD

**Issue by jianghong** [bytecodealliance/javy#316]
## What is the idea?
Introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) into Javy

Check out https://rust-fuzz.github.io/book/cargo-fuzz.html to start

## What problem does it solve?
It could help us be more confident in our changes and to prevent any regression.

**Comment by saulecabrera** [comment]
The initial skeleton for the fuzzing infrastructure was introduced in https://github.com/bytecodealliance/javy/pull/699. I'll go ahead and close this issue.
