### ISSUE TITLE
Fix Node 14 incompatibility in cli npm packages

### ISSUE THREAD

**Issue by jianghong** [bytecodealliance/javy#322]
It would be nice to support Node 14 since that is what is recommended in the Shopify Docs for app development 

Original issue https://github.com/Shopify/javy/issues/304

**Comment by surma** [comment]
Fwiw, we should rather change/update our Shopify Docs. [Node 14 reaches End Of Life in 4 days](https://github.com/nodejs/release#release-schedule).

**Comment by jianghong** [comment]
Oh thanks for the heads up! I don't think we need to spend time on this issue then
