### ISSUE TITLE
Add build support for docs.rs

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/javy#336]
## What is the idea?

Add support for building `quickjs-wasm-sys` and everything depending on it to docs.rs.

## What problem does it solve?

Docs.rs is a common place for viewing crate documentation, and at the moment, `quickjs-wasm-sys` and crates that depend on it like [quickjs-wasm-rs](https://docs.rs/crate/quickjs-wasm-rs/0.1.4) do not build successfully on docs.rs.

<img width="1282" alt="Screenshot 2023-05-01 at 13 25 06" src="https://user-images.githubusercontent.com/154890/235496821-eebaea22-29ee-40fa-86f2-5edb57501066.png">

**Comment by jeffcharles** [comment]
Surma's changes to the build script were made after the 1.0.0 release of the crate. We need to release a new version of the `quickjs-wasm-sys` crate to see if the crate will build successfully on docs.rs. If the new version of the crate builds successfully, we can update all of the other crates to use that version of `quickjs-wasm-sys` and they should build correctly on docs.rs.

**Comment by jeffcharles** [comment]
Opened https://github.com/bytecodealliance/javy/pull/445 to bump quickjs-wasm-sys version in preparation for publishing

**Comment by jeffcharles** [comment]
`quickjs-wasm-sys` v1.1.0 has been published. I'm waiting for docs.rs to pick up the new version of the crate and to try building it to confirm it works. If it does, we can proceed with updating the versions of the other Javy crates to also fix their docs.rs pages.

**Comment by jeffcharles** [comment]
`quickjs-wasm-sys` v1.1.0 is still failing to build in docs.rs.

https://docs.rs/crate/quickjs-wasm-sys/1.1.0/builds/874424 shows the output. Relevant logs are:

```
[INFO] [stderr]    Compiling quickjs-wasm-sys v1.1.0 (/opt/rustwide/workdir)
[INFO] [stderr] error: failed to run custom build command for `quickjs-wasm-sys v1.1.0 (/opt/rustwide/workdir)`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/quickjs-wasm-sys-07c92e724ddef2eb/build-script-build` (exit status: 1)
[INFO] [stderr]   --- stdout
[INFO] [stderr]   cargo:rerun-if-env-changed=QUICKJS_WASM_SYS_WASI_SDK_PATH
[INFO] [stderr]   cargo:rerun-if-env-changed=QUICKJS_WASM_SYS_WASI_SDK_MAJOR_VERSION
[INFO] [stderr]   cargo:rerun-if-env-changed=QUICKJS_WASM_SYS_WASI_SDK_MINOR_VERSION
[INFO] [stderr] 
[INFO] [stderr]   --- stderr
[INFO] [stderr]   Error: failed to lookup address information: Temporary failure in name resolution
```

That looks like a DNS failure error message to me. We'll need to do more work to resolve this.

**Comment by surma** [comment]
Docs.rs might just be blocking network access altogether to prevent abuse.

**Comment by jeffcharles** [comment]
Confirmed that docs.rs blocks network access, https://docs.rs/about/builds#hitting-resource-limits:
> - Network access will not be enabled for any crate.

We can request for Ubuntu packages to be added to the build environment. There is one for `wasi-libc`. And it _should_ be possible to configure a standard clang install to use that libc as a sysroot. That said, I'm having trouble compiling a basic C program in Ubuntu using upstream clang and `wasi-libc`. Currently getting a `wasm-ld-14: error: unable to find library -lgcc`. Not sure why it's calling out to GCC but I have GCC installed so I'm not sure how to resolve that right now.

There is also a disclaimer on the WASI SDK page:
> One could also use a standard Clang installation, build a sysroot from the sources mentioned above, and compile with --target=wasm32-wasi --sysroot=/path/to/sysroot. In this scenario, one would also need the libclang_rt.builtins-wasm32.a objects available separately in the [release downloads](https://github.com/WebAssembly/wasi-sdk/releases) which must be extracted into $CLANG_INSTALL_DIR/$CLANG_VERSION/lib/wasi/.

I tried installing that archive file with no luck. Installing the archive file on the docs.rs build server would not be possible without copying the clang installation (which should be doable) since docs.rs will fail builds that try to write to locations outside the `OUT_DIR`. But, I'm not sure how to proceed given I can't get a barebones WASI build working on Ubuntu with upstream clang, `wasi-libc`, and the clang runtime archive installed.

**Comment by jeffcharles** [comment]
Opened https://github.com/rust-lang/crates-build-env/issues/136 on the build environment to see if the upstream maintainers have any thoughts.

**Comment by jeffcharles** [comment]
I've got a work-in progress on https://github.com/bytecodealliance/javy/compare/jc.docsrs-support?expand=1. It seems to work on an Ubuntu docker container.

**Comment by jeffcharles** [comment]
https://github.com/rust-lang/crates-build-env/pull/137 was merged but won't be deployed until next week. There is a docker container I can use to test but the setup looks like it may rely on `docker-compose` which we don't have access to due to Docker Desktop licensing changes. Depending on how other work goes, I might be able to try it later today. Otherwise I'll mark #453 as ready for review after I get back from vacation and we can try with a pre-release version to see if it builds the docs successfully.

**Comment by jeffcharles** [comment]
Merged https://github.com/bytecodealliance/javy/pull/453. Will publish a pre-release of the crate after CI passes to see if docs.rs can build it.
