### ISSUE TITLE
Gracefully handle JS execution errors

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/javy#360]
## What is the idea?

At the moment, we are calling `unwrap` on the result of executing JavaScript (e.g. https://github.com/Shopify/javy/blob/main/crates/core/src/lib.rs#L67), we should gracefully handle the error case of the result. 

This is also the case in https://github.com/Shopify/javy/blob/main/crates/core/src/main.rs#L32

## What problem does it solve?

Reduce the noise generated by Rust when unwrapping an error value and provide better feedback when JS execution fails.

**Comment by nickwesselman** [comment]
Ideally we would output the JavaScript stack trace as part of this, assuming it's available in QuickJS.
