### ISSUE TITLE
quickjs-wasm-rs stack-overflow

### ISSUE THREAD

**Issue by gc-victor** [bytecodealliance/javy#385]
I have a "stack-overflow" error. It looks like that comes from QuickJS. 

Did you face it? How did you solve it?

Possible solution:

- https://github.com/bellard/quickjs/issues/97#issuecomment-947553138

QuickJS related issues:

https://github.com/bellard/quickjs/issues?q=stack+overflow

**Comment by gc-victor** [comment]
I have found the issue. It turned out to be a global object being used within a loop. To fix it, I assigned the object to a variable outside the loop within the function that was utilizing it. At least for now, it works.

**Comment by surma** [comment]
Can you provide us with a small reproducible example? This seems like a bug worth fixing.

**Comment by gc-victor** [comment]
I have try to reproduce it again, but sadly I can not. Sorry

**Comment by gc-victor** [comment]
If I face it again, I will open a new issue and provide an example.
