### ISSUE TITLE
Support for network calls

### ISSUE THREAD

**Issue by munjalpatel** [bytecodealliance/javy#386]
## What is your question?

Is making network calls from the Javy compiled JS wasm possible?

**Comment by jeffcharles** [comment]
No, it's not possible with the Javy CLI at the time being.

What you can do is use the `javy` and `javy-apis` crates available on crates.io to create your own JS runtime that runs inside a Wasm module, and then write some Rust to register one or more custom APIs with that JS runtime that calls through to one or more custom host functions, and then compile that to WASI. And then optionally you can create your own version of the CLI that uses the WASI module you build. But you will also need to provide implementations for any custom host functions you define this way in your runtime environment as there is not currently a standardized way of making network calls via WASI.

**Comment by jeffcharles** [comment]
Closing this for now. Feel free to comment if you feel that your question has not been answered.
