### ISSUE TITLE
Error while Building

### ISSUE THREAD

**Issue by Thorngage** [bytecodealliance/javy#390]
Hello, I'm a complete Noob trying to test out Javy to compile a super simple .js file to wasm. 
I'm doing this research for a team of much more experienced people than me that, however, are not versed enough in english to do this research themselves (the almost totality of documentation regarding Javy is in english), so really forgive me if whatever I'm doing is obviously wrong, but most of what I've been doing, I did not know what it was.

So I'm working on a windows machine, after installing with much difficulty the WSL (using Ubuntu as a distro)
I've been following the commands in the readMe documentation (could use some more details, the need to install rust is not clear to a newbie, as are some things that don't work without installing others first, the rustup and cargo commands did not work at first, but fortunately Linux's terminal is very helpful in identifying problems)
The first big hurdle was the error linker 'cc' not found, I found out from some other website that APT update was necessary, so maybe adding a mention to update and eventually run 

`sudo apt-get update`
and
`sudo apt install build-essential`
before installing wasmtime-cli could help other newbies like me

After that I kept getting an error message of not finding the Cargo.toml file in the directory in the first building step, however after a while I realized that the command
`cargo build -p javy-core --target=wasm32-wasi -r`
was to be run inside the javy directory (was I right?)

I ran the command there,  it seemed to go all right but now i get an extensive error message, apparently i needed to instal a pkg-config

i tried running
`apt install pkg-config`
but then when I re-run the command inside javy i get this

```
  Compiling openssl-sys v0.9.88
   Compiling openssl-macros v0.1.0
   Compiling tokio-macros v1.7.0
   Compiling minimal-lexical v0.2.1
   Compiling httparse v1.8.0
   Compiling once_cell v1.16.0
   Compiling native-tls v0.2.11
   Compiling futures-channel v0.3.27
error: failed to run custom build command for `openssl-sys v0.9.88`

Caused by:
  process didn't exit successfully: `/home/michele/javy/target/release/build/openssl-sys-ca1c01bffa9b51a6/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "openssl"` did not exit successfully: exit status: 1
  error: could not find system library 'openssl' required by the 'openssl-sys' crate

  --- stderr
  Package openssl was not found in the pkg-config search path.
  Perhaps you should add the directory containing `openssl.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'openssl' found


  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.88

  ', /home/michele/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.88/build/find_normal.rs:190:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
``` 

At this point I'm stuck, any suggestions? what am I missing?

**Comment by Thorngage** [comment]
Oh I see, I never saw the releases tab so I assumed this was compile-yourself project. Thanks for your help, I hope the suggestions were insightful!

**Comment by Thorngage** [comment]
I'm having another issue at this point:

I downloaded
javy-x86_64-windows-v1.0.1.gz 

Extracted the .exe, but when I run it nothing happens

**Comment by jeffcharles** [comment]
> but when I run it nothing happens

Can you be more specific about how you ran it? Was it with CMD, Powershell, Cygwin, or some other shell? What arguments did you pass? Copying the exact invocation along with any output on stdout or stderr would be helpful. What was the process exit code?

**Comment by Thorngage** [comment]
I literally just double clicked the .exe file

**Comment by surma** [comment]
Run it from a terminal, then you can see the output :)
