### ISSUE TITLE
Access the exported methods from a script

### ISSUE THREAD

**Issue by Angelmmiguel** [bytecodealliance/javy#396]
## What is the idea?

Currently, Javy supports ECMAScript modules (ESM) via the [`compile_module` JSContext method](https://github.com/bytecodealliance/javy/blob/cfd4f078cb85e3de5630d05a7ed4ef58b2289b32/crates/quickjs-wasm-rs/src/js_binding/context.rs#L113). It interprets and run any code that includes keywords from the ESM specification like `import / export`.

However, we cannot access to the these exported methods and values after it finishes. For example, given the following JavaScript code, I would like to access to the `fetch` in the exported object: 

```javascript
export default {
  async fetch(request) {
    const body = `Hello world!`;
    return new Response(body);
  },
};
```

The goal is to expose these methods at the `quickjs-wasm-rs` level, so we can build custom JavaScript runtimes on top of the `javy` crate. For now, I'm not thinking on fetching these exports and setting them as "exported functions" in the Wasm module from the `javy-cli`.

## What problem does it solve?

ESM modules are more and more common in the JavaScript ecosystem. For example, different projects from the [WinterCG](https://wintercg.org/) started using ESM modules as the way to define workers / functions in their platforms:

```javascript
// From
addEventListener("fetch", event => { 
  return event.respondWith(new Response("Hello World")); 
}); 

// To
export default {
  async fetch(_request) {
    return new Response("Hello world");
  },
};
```

For example:

* [Vercel](https://github.com/vercel/examples/blob/main/edge-functions/hello-world/api/edge.ts)
* [Cloudflare](https://github.com/cloudflare/workers-sdk/blob/main/templates/worker/index.js)

We want to offer the same option in Wasm Workers Server, that relies on Javy for the JavaScript runtime. We need access to those exported methods so we can call those functions from the Rust side. 

Here you can find the related issue (vmware-labs/wasm-workers-server/issues/149).

**Comment by jeffcharles** [comment]
I am also actively investigating how to do this for one of our use cases too 😄

**Comment by Angelmmiguel** [comment]
> I am also actively investigating how to do this for one of our use cases too 😄

That's great @jeffcharles! If there's any branch / fork related to this effort, I would be really happy to check it and try to contribute. Any guidance on the required changes here would be helpful to start playing with it 😄

**Comment by Angelmmiguel** [comment]
> I use a simple replacement. It is not a fancy solution, but it does its work.
> 
> [https://github.com/gc-victor/js-wasm-workers-runtime/blob/main/crates/runtime/src/lib.rs#L31](https://github.com/gc-victor/js-wasm-workers-runtime/blob/f395d018488884f687a9dd94121c14bb05a17e88/crates/runtime/src/lib.rs#L31)

Yes, I'm using a similar replacement for some tests now hehe.

**Comment by jeffcharles** [comment]
I've got an approach that seems to work though it's a bit messy in https://github.com/bytecodealliance/javy/compare/jc.exported-func-invoke-example?expand=1.

I couldn't find a C API that enables us to retrieve the function directly unfortunately. There are C APIs for working with the exports list of a module (for example, `find_export_entry`) but they're internal to QuickJS. But you can import the module and its functions by evaluating some JavaScript with the appropriate eval type flag set. There is a ~10% performance decrease compared to calling a function assigned to `globalThis` in Rust.

**Comment by Angelmmiguel** [comment]
> I've got an approach that seems to work though it's a bit messy in https://github.com/bytecodealliance/javy/compare/jc.exported-func-invoke-example?expand=1.
> 
> I couldn't find a C API that enables us to retrieve the function directly unfortunately. There are C APIs for working with the exports list of a module (for example, `find_export_entry`) but they're internal to QuickJS. But you can import the module and its functions by evaluating some JavaScript with the appropriate eval type flag set. There is a ~10% performance decrease compared to calling a function assigned to `globalThis` in Rust.

Thank you @jeffcharles! I think this may work. In my case, I'm using the `global` object to get the result of the script. I will need to define custom methods to extract the information, so I don't rely on a specific field in the `globalThis` object.

**Comment by AndreLion** [comment]
So, before the exported methods is officially supported, how can I execute the wasm built by Javy with browser API `WebAssembly.instantiate()`, in other words, how can I send `stdin` into wasm in browser?

Thanks and btw really great work @jeffcharles

**Comment by jeffcharles** [comment]
> how can I execute the wasm built by Javy with browser API `WebAssembly.instantiate()`, in other words, how can I send stdin into wasm in browser?

You'll need to use a browser implementation of WASI. Using https://github.com/bjorn3/browser_wasi_shim _may_ work. I don't have a browser example unfortunately.
