### ISSUE TITLE
Command failed with exit code 1:

### ISSUE THREAD

**Issue by ellowwwteam** [bytecodealliance/javy#450]
## How to solve following issue?

─ external error ──────────────────────────────────────────────────────────────

Error coming from `npm exec -- javy compile -d -o /home/hp/shopifyapp/CartTransf
orm/specialized-revenue-app/extensions/cart-transformer/dist/function.wasm
dist/function.js`

Command failed with exit code 1: npm exec -- javy compile -d -o
/home/hp/shopifyapp/CartTransform/specialized-revenue-app/extensions/cart-transf
ormer/dist/function.wasm dist/function.js

**Comment by jeffcharles** [comment]
The correct command would be `npm exec -- javy-cli compile [...]`.

**Comment by makrandgupta** [comment]
running into this as well, you can read more here: https://github.com/Shopify/cli/issues/2626

For now adding `javy-cli` to the project fixed the issue for me

**Comment by jeffcharles** [comment]
Diagnosed the problem was using an earlier version of `javy-cli` that had a bug in it that was fixed in 0.1.8.
