### ISSUE TITLE
Running Javy without Node/NPM

### ISSUE THREAD

**Issue by sandstrom** [bytecodealliance/javy#451]
We've tried out Javy and it works great overall.

One thing we didn't want to do, was to download node/npm only to install Javy. We're using JS for custom scripts, but in a context where we otherwise don't use any Javascript.

So instead, we're downloading the following binaries manually:

- Javy FS: https://registry.npmjs.org/javy/-/javy-%{version}.tgz
- Javy Provider: https://github.com/bytecodealliance/javy/releases/download/v%{version}/javy-quickjs_provider.wasm.gz
- Javy: https://github.com/bytecodealliance/javy/releases/download/v%{version}/javy-%{arch}-%{os}-v%{version}.gz
- ESbuild: https://registry.npmjs.org/@esbuild/%{os}-%{arch}/-/%{os}-%{arch}-%{version}.tgz

This was fairly easy to setup and works really well! 🏅 

As this project advances (and presumably adopts componentize-js as a dependency in the future?), it would be neat if Javy was still able to operate without a node environment, as a single binary or a collection of binaries (like it can be used today, as mentioned above).

I understand that this depends a bit on what direction you want to take the project, and what tooling you'd like to base it on (currently bytecodealliance/jco seems to be used, which is obviously locked into the Node ecosystem, but there is also the wasm-tools cargo create etc).

Nothing major, but wanted to mention this feedback.

**Comment by jeffcharles** [comment]
Hi, thanks for the feedback! I can certainly understand wanting to pull in a minimal set of dependencies.

If you are willing to forgo the use of the `javy` NPM or package or any other NPM packages, then you don't need to use Node, NPM, or esbuild.

We're not currently planning on introducing hard dependencies on Node.

**Comment by sandstrom** [comment]
Sounds great, thanks @jeffcharles!
