### ISSUE TITLE
JS Source maps?

### ISSUE THREAD

**Issue by william-stacken** [bytecodealliance/javy#462]
## What is your question?
Assuming my understanding is up to date, Javy requires a bundler like Esbuild to compile Javascript that depends on external node packages like `javy-fs`. This means that file and line number information in back traces generated by the Quick JS provider do not correspond to the original unbundled javascript code. Esbuild can emit a source map file, but is there any way to supply this file to Javy or the Quick JS runtime such that it generates back traces that are consistent with the original javascript code?

**Comment by saulecabrera** [comment]
Hi @william-stacken, currently there's no way to map the source location information back to the original JavaScript source and as far as I know there's no straightforward way to achieve this with QuickJS. In theory if QuickJS had a way to do this, we could bundle the sourcemaps in the generated Wasm module and find a way interpret them and display them.

**Comment by saulecabrera** [comment]
I'm going to go ahead an close this issue as I believe that the main question was addressed, but please feel free to continue to conversation if there are any follow up questions.
