### ISSUE TITLE
How to run on windows 11

### ISSUE THREAD

**Issue by Mona-Bindary** [bytecodealliance/javy#463]
Hello, 

I have a question, how to run it on windows. I used npm to install it but it gives unexpected results when I run the commands that convert

Best Regards
Mona

**Comment by saulecabrera** [comment]
Hi @Mona-Bindary,

The easiest way to run Javy on Windows is through [npm](https://www.npmjs.com/), via `npx javy-cli`, else you can build it from source. 

Can you please paste what command you used and what is the output that you're getting?

**Comment by jeffcharles** [comment]
I'm going to close this issue since it's been a little over a month without response. Please feel free to re-open if there is a problem that has not been resolved 🙂.
