### ISSUE TITLE
[QUESTION] Is there any possible to run javy itself in wasm runtime?

### ISSUE THREAD

**Issue by jjeffcaii** [bytecodealliance/javy#466]
## What is your question?
I want to compile a javascript to wasm over javy in a wasm vm, for example:
```
vm := new WasmVM()
javyModule := vm.import("javy.wasm")
wasmByteCodes := javyModule.call("compile", "function helloworld() { return 'hello world';}")
helloModule := vm.import(wasmByteCodes);
helloModule.call("helloworld") // will return "hello world"
```

Thanks!

**Comment by jeffcharles** [comment]
No that's not possible at the moment.

For compilation with static linking (that is, the Wasm module contains the QuickJS engine as well as the JS to execute), we require using Wizer to load the JS source code into the Wasm module and Wizer uses Wasmtime to invoke the preinitialization function and Wasmtime cannot be run from within a Wasm VM.

For compilation with dynamic linking (that is, the Wasm module contains QuickJS bytecode and invokes an imported execute function from the `javy_quickjs_provider.wasm` module), hypothetically it likely would be possible to build a Wasm module that could perform that compilation. The `walrus` crate performs most of the work of generating the module. But that separate module doesn't exist today and we use the same CLI for both static and dynamic linking which means the CLI can't be compiled to Wasm.

Also it's probably worth pointing out that the example would require a more complicated interface. Wasm functions do not support string or byte array parameters or return values, just numbers. So for something like `compile`, you would need to call a memory allocation function, copy a byte array containing the string into the instance's memory to that address, then pass the address and length of the byte array to compile. And `compile` would need to return an address to a wide pointer containing the address and length of the byte array it created and you'd need to copy that byte array into the host. You'd also need to use something like WIT or SWC or both to inform the compiler of what functions to export from Wasm.

Hopefully that answers your question!

**Comment by jjeffcaii** [comment]
Thanks for the detailed answer! 👍🏽
