### ISSUE TITLE
NodeJS vs Javy performance

### ISSUE THREAD

**Issue by mrdivyansh** [bytecodealliance/javy#480]
## What is your question?
I wanted to know why this JavaScript code ran faster on NodeJS than Javy-compiled WASM.

```js
// index.js

generateStr(1000000);

// Generates random strings
function generateStr(length) {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const charactersLength = characters.length;
  let counter = 0;
  while (counter < length) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
    counter += 1;
  }
  return result;
}
```

Run on NodeJS
```sh
time node index.js # 0.11s user 0.02s system 103% cpu 0.121 total
```

Run wasmtime
```sh
npx javy compile index.js -o index.wasm
time wasmtime index.wasm # 12.67s user 0.10s system 103% cpu 12.284 total
```

**Comment by jeffcharles** [comment]
The short answer is that NodeJS uses the V8 JavaScript engine which can _just in time_ (JIT) compile hot loops in JavaScript (like the while loop in your example) to native code while Javy uses the QuickJS interpreter to execute JavaScript which can't JIT-compile JavaScript to native code.

To provide a little more context, Javy doesn't compile your JavaScript to WebAssembly bytecode. A Wasm module produced by Javy contains a preinitialized QuickJS interpreter that's been compiled to WebAssembly bytecode and a QuickJS bytecode representation of your JavaScript source code. At runtime, Javy has the QuickJS interpreter run the QuickJS bytecode. When using Wasmtime as your runtime, Wasmtime uses the Cranelift compiler to convert the Wasm bytecode (the QuickJS interpreter and our code for loading the QuickJS bytecode into it) into native code, but it will never convert the JavaScript source into native code, instead relying on the QuickJS interpreter to execute the JavaScript bytecode.

Does that answer your question?

**Comment by louisvangeldrop** [comment]
I have noticed that if you do: 

1.  wamrc -o index.aot  index.wasm
2. iwasm index.aot 

gives an improvement of roughly 20% compared to: wasmtime index.wasm

There is also a gain is in the size difference of iwasm.exe+index.aot compared to wasmtime.exe+index.wasm.

**Comment by jeffcharles** [comment]
That's cool that AOT-compiling with WAMR is able to have that kind of difference. I tried AOT-compiling with Wasmtime and was only able to get a ~3% performance improvement for this specific program.

**Comment by jeffcharles** [comment]
I'm going to close this issue as the question has been answered. Please feel free to respond with any follow up questions!
