### ISSUE TITLE
How to call host functions from javascript?

### ISSUE THREAD

**Issue by relcodedev** [bytecodealliance/javy#554]
## How to call host functions from javascript?

i am using wasmtime from dotnet.  I have a dotnet console app hosting wastime to run the wasm module.
I can run the wasm module from main function but I am trying to call a host function from javascript. 
This works from a rust wasm module. I tried to review all of the docs to see if there is a way to call external functions.

**Comment by jeffcharles** [comment]
The Javy _CLI_ released as part of this project does not support calling custom host functions. We do provide documentation on [extending Javy](https://github.com/bytecodealliance/javy/blob/d6de349d3e545391e2c2f85e5b9d7926789413df/docs/extending.md) so you can use the [javy Rust crate](https://crates.io/crates/javy) to build your own equivalent of the Javy CLI or JavaScript Wasm module that can provide support for calling custom host functions from JavaScript.

Let me know if that helps!

**Comment by relcodedev** [comment]
Thanks.  Yes, I found the earlier question with response after I submitted.
