### ISSUE TITLE
Imported functionallity from the host

### ISSUE THREAD

**Issue by william-stacken** [bytecodealliance/javy#599]
## What is your question?
We are currently using Javy and are very happy with it! The way we are using the Wasm modules output by Javy currently is that, from the host runtime we are providing a JSON input over its stdin and parsing a JSON output from its stdout. The Wasm modules are written by our users and most of them don't need all the data in the JSON. As we add more data to the JSON input, it keeps getting larger and it takes longer to produce.

Performance could be improved if we could, instead of providing all the data the Wasm module could possibly need before it is invoked, have the Wasm module be able to request the information that it actually needs through imported functions from the host (custom ones outside of the WASI standard). Is this something that Javy plans to support in the future?

**Comment by jeffcharles** [comment]
Have you read [our documentation on extending Javy](https://github.com/bytecodealliance/javy/blob/main/docs/extending.md), which includes adding custom APIs?

To summarize what's in there, we have a number of crates published to crates.io which we recommend using and then writing your own CLI and javy-core implementation that re-use those crates.

**Comment by william-stacken** [comment]
Thanks a lot!
