### ISSUE TITLE
[quickjs-wasm-sys] `JS_DupValue` is missing

### ISSUE THREAD

**Issue by surma** [bytecodealliance/javy#607]
[QuickJS has two functions](https://bellard.org/quickjs/quickjs.html#JSValue) to increment and decrement a JSValue’s reference count: `JS_DupValue` and `JS_FreeValue` respectively.

`quickjs-wasm-sys` has the latter ([`quickjs_wasm_sys::__JS_FreeValue`](https://docs.rs/quickjs-wasm-sys/latest/quickjs_wasm_sys/fn.__JS_FreeValue.html)) but not the former. This is necessary when working with raw QuickJS values and wanting to prevent them from getting GC’d.

I took a quick look but could not find a quick fix to this.

**Comment by saulecabrera** [comment]
@surma, this PR https://github.com/bytecodealliance/javy/pull/609 should address this issue.

**Comment by saulecabrera** [comment]
Oh actually there's a small issue with `JS_ValueConst`, I'll see if I can fix it.

**Comment by saulecabrera** [comment]
I think it should be fixed.
