### ISSUE TITLE
Urgent help required : How to debug this ? Getting error at some line no in function.mjs

### ISSUE THREAD

**Issue by redoC-A2k** [bytecodealliance/javy#625]
## What is your question?
This is the error I am getting when compiling a js file with our extended javy 
```sh
called `Result::unwrap()` on an `Err` value: Uncaught SyntaxError: invalid property name
    at function.mjs:148

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: JS compilation failed
```

```js
import { Hono } from "hono";


const app = new Hono();

app.get("/",(c)=>{
    // return c.text({"message":"Hello World!"});
    return c.text("hello world")
})

app.notFound((c) => {
    return c.text("404 not found", 404);
});

app.fire();

```

I compiled a output file esbuild and then compiling output js file with javy .
But unable to determine where this uncaught syntax error happening in my js code.
Please help me

**Comment by redoC-A2k** [comment]
I basically want to know what is written at line 148 in function.mjs file

**Comment by redoC-A2k** [comment]
can anybody help

**Comment by saulecabrera** [comment]
> I compiled a output file esbuild and then compiling output js file with javy .

The best bet in this situation is to inspect the file that esbuild created and inspect the contents of line 148. Have you tried that?

**Comment by redoC-A2k** [comment]
So does the file created by esbuild maps directly to function.mjs ?

**Comment by saulecabrera** [comment]
`function.mjs` is simply the name given to the file containing the JS source passed in to Javy. In that sense if an error is reported in `function.mjs` you should look at the file, line and column of the file created by esbuild.

**Comment by redoC-A2k** [comment]
Ohk , thanks for helping

**Comment by redoC-A2k** [comment]
Ohk , thanks for helping .
