### ISSUE TITLE
accessing arguments.callee leads to TypeError: invalid property access

### ISSUE THREAD

**Issue by truff77** [bytecodealliance/javy#645]
Hello,

I'm trying to use this javascript code: 
```javascript
function myFunction() {
  console.log(arguments.callee);
}

myFunction();
```

and it generates TypeError: invalid property access. 

Is this a normal behavior ? 

thank you in advance !

**Comment by jeffcharles** [comment]
Yes this is normal behaviour. Javy compiles and executes the provided JS as an ESM module which implies [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) and `arguments.callee` is not allowed in strict mode.

**Comment by truff77** [comment]
Hi @jeffcharles thank you for the fast answer, this makes total sense now !
